### PR TITLE
Italian Language

### PR DESCRIPTION
**Pull request by Drijon7577**
I did this pull request to
- [x] Add translations
- [ ] Fix translations

### Changed files
1. `it/context.info`
2. `it/interaction.help`
3. `it/interaction.info`
4. `it/interaction.language`

### CODE REVIEW

**Comment by Drijon7577** [comment]
Sorry that i didn't fill it up haha

Here is it:

Add these files for Italian Language :)

**Review by Luna-devv — COMMENTED** [review]
it is `it/` and not `ita/`

**Comment by Drijon7577** [comment]
If i would have done IT in VSC for me it would have opened another folder with another context lol

**Review by Luna-devv — CHANGES_REQUESTED** [review]
Yeah please rename the folder from `ita` to `it`, once you did I'll approve this pull request and merge it.

**Comment by Drijon7577** [comment]
Changed it, Update now and it should have worked

**Review by Luna-devv — APPROVED** [review]
Looks good! Thank you for your translation <3

**Comment by Drijon7577** [comment]
No Problem <3

**Pull request merged**
